// Antics free question pools for the web generators.
// Sourced from the already-public guide pages (deck-derived, non-spicy).
// The app holds ~2,000 cards; these free pools funnel to it.
window.ANTICS_QUESTIONS = {
 "nhie": [
  "Sent a message to the group chat that was meant for one person.",
  "Given my number to someone just to be polite.",
  "Practised kissing on my hand or a pillow.",
  "Made a playlist about someone who never knew about it.",
  "Used a cheesy chat-up line that actually worked.",
  "Slid into someone's DMs.",
  "Been chatted up and only realised on the way home.",
  "Agreed to a date I never intended to go on.",
  "Been on a date purely for the free food.",
  "Not recognised a date from their photos.",
  "Rehearsed a \"casual\" text for twenty minutes.",
  "Sent a risky text and turned my phone face down like a coward.",
  "Deleted a message and left them staring at \"this message was deleted\".",
  "Fancied someone purely because they ignored me.",
  "Lost interest the second they liked me back.",
  "Got the ick mid-date and left early.",
  "Stood up a date.",
  "Left a date early because it was going that badly.",
  "Texted a mate to fake an emergency mid-date.",
  "Been the fake emergency for someone else's bad date.",
  "Given someone a fake name or number.",
  "Cancelled a date because a better offer came in.",
  "Been cancelled on, then seen them out that same night.",
  "Recognised someone from a dating app in public and pretended I didn't.",
  "Turned up to a first date already knowing their whole life story from their socials.",
  "Flirted with two people at the same party.",
  "Flirted my way to a free drink.",
  "Worn an outfit purely because one specific person would be there.",
  "Been dumped by text.",
  "Dumped someone by text.",
  "Cried over someone I dated for less than a month.",
  "Stalked an ex's new partner online.",
  "Got back with an ex I swore I was done with.",
  "Had someone saved as \"DO NOT TEXT\", and texted them.",
  "Blocked someone, then unblocked them just to have a look.",
  "Screenshotted a conversation and sent it to the wrong person.",
  "Thrown up in a taxi.",
  "Woken up somewhere with no idea how I got there.",
  "Fancied someone in this room.",
  "Had a dream about someone in this room.",
  "Kissed someone whose name I never learned.",
  "Kissed two people in the same night.",
  "Had a one-night stand.",
  "Kissed a mate's ex.",
  "Matched with a friend's ex on a dating app.",
  "Been in a situationship I refused to call a situationship.",
  "Ghosted someone and then bumped into them in person.",
  "Done a walk of shame past someone I knew.",
  "Snuck out before someone woke up.",
  "Got with someone in this friendship group."
 ],
 "wyr": [
  "Have your search history projected at your next party, or have your DMs printed and handed to your parents?",
  "Your group chat leaks, or your camera roll leaks?",
  "Everyone sees your screen time, or everyone sees your bank balance?",
  "Kiss the person on your left, or read out your last five searches?",
  "Your body count is public knowledge, or your bank balance is public knowledge?",
  "Get caught deep-stalking their profile, or get caught rehearsing a conversation with them?",
  "Accidentally like your crush's photo from 2019, or accidentally send your crush a screenshot of their own profile?",
  "All your exes have your live location, or all your exes are in one group chat?",
  "Swap exes with the person on your left, or swap phones with them for a week?",
  "Hear this room rate your kissing out of ten, or never find out?",
  "Everyone knows who you fancy, or the person you fancy reads everything you've said about them?",
  "Text your crush how you feel right now, or never be able to message them again?",
  "Date your boss, or get back with your ex?",
  "Every person you've ever kissed walks in right now, or your last month of DMs is read out loud?",
  "Kiss your best mate's sibling, or kiss your sibling's best mate?",
  "Marry the best sex you've ever had, or marry the best chat you've ever had?",
  "Date someone who still lives with their ex, or date someone who tells their mum everything. Everything.",
  "Only date people your exes approve of, or only date people your parents pick?",
  "Snog an ex every New Year's Eve forever, or never kiss anyone at midnight again?",
  "One-night stands only, forever, or your group chat arranges your marriage?",
  "Your ex writes your dating bio, or your mum picks your profile photos?",
  "Your ex plans your wedding, or your boss plans your last night of freedom?",
  "Your last relationship becomes a documentary, or your next one is a live reality show?",
  "Only first dates for the rest of your life, or married by Monday to someone in this room?",
  "Relive your first ever kiss weekly, or watch your first ever kiss on video with this group?",
  "Know exactly how you die, or know exactly when you die?",
  "Be famous but broke, or be rich but completely unknown?",
  "Give up sex for a year, or give up your phone for a year?",
  "Only ever whisper, or only ever shout?",
  "Have to sing everything you say, or have to dance everywhere you walk?",
  "Everyone reads your mind for a day, or you read everyone's minds for an hour?",
  "Only speak in questions, or only speak in rhyme?"
 ],
 "mlt": [
  "Text an ex tonight.",
  "Get with someone in this room.",
  "Have the messiest situationship.",
  "Stalk their ex online at 2am.",
  "Have already texted their ex this week.",
  "Send a risky text and blame it on the wine.",
  "End up kissing someone in this room tonight.",
  "Have kissed the most people in this room.",
  "Get banned from a dating app.",
  "Get engaged after three months.",
  "Marry someone they met that same night.",
  "Get married in Vegas.",
  "Turn a one-night stand into a three-year relationship.",
  "Be planning the wedding after one date.",
  "Get a partner's name tattooed within a year of meeting.",
  "Leave you on read but watch every story.",
  "Become a stage-five clinger.",
  "End up in a love triangle.",
  "Fall in love with a stranger on holiday.",
  "Triple-text someone without shame.",
  "Start drama in the group chat.",
  "Ghost someone in this room.",
  "Get kicked out of a club.",
  "Be lying in this game right now.",
  "End up on Love Island.",
  "Have the most chaotic camera roll.",
  "Flirt their way out of trouble.",
  "Flirt their way INTO trouble.",
  "Get arrested on a night out.",
  "Read everyone's messages if given one free chance.",
  "End the night with a stranger's number and no memory of getting it.",
  "Get with their boss.",
  "Actually pull a celebrity.",
  "End up with a sugar daddy or sugar mummy.",
  "Marry rich and retire at 30.",
  "Get catfished.",
  "Have a secret account nobody knows about.",
  "Have the most unhinged search history.",
  "Ditch the group for someone they met an hour ago.",
  "Have a whole second life nobody here knows about."
 ],
 "tod": [
  "Who in this room would you most want to kiss, if you had to pick?",
  "Read out the last text you sent.",
  "What's the biggest red flag you've ignored because they were hot?",
  "Who did your last risky text go to?",
  "Have you ever kissed anyone in this room?",
  "What's your toxic trait, according to your exes?",
  "What's the most embarrassing thing in your camera roll right now? Describe it.",
  "Whose profile did you last look at on social media?",
  "What's the worst thing you've done on a night out?",
  "If you HAD to date one person in this room, who?",
  "What's the biggest ick someone's ever given you?",
  "What was your honest first impression of the player on your left?",
  "Which two people in this room would make the best couple?",
  "What's the biggest lie you've told a parent?",
  "Have you ever ghosted someone? What's your excuse?",
  "Who in this room would you trust least with your phone unlocked?",
  "Who in this room has the best chat on a night out, and the worst?",
  "If you had to swap lives with someone in this room, who and why?",
  "What's the most trouble you ever got in at school?",
  "What's the cringiest thing you've ever posted online?",
  "Let the group scroll your camera roll for 20 seconds. You may veto ONE album.",
  "Show the group your screen-time report. No explanations allowed.",
  "Text your most recent match \"you crossed my mind today x\".",
  "Kiss someone in this room (cheek counts, cowards).",
  "Read out the last thing you typed in your notes app.",
  "Do your best impression of the player on your left until they laugh.",
  "Let the player on your right send one emoji from your phone to anyone they choose.",
  "Perform your go-to flirty dance move on the count of three.",
  "Swap phones with the player on your left until your next turn.",
  "Demonstrate your best chat-up line on the player on your left with full commitment.",
  "Moan the alphabet until someone laughs.",
  "Show the last five photos in your camera roll, no skips (one veto).",
  "Twerk for 15 seconds.",
  "Tell the group your honest first impression of everyone here, one by one.",
  "Sit on the lap of the player on your left until your next turn.",
  "Make up a 30-second rap about the person on your left.",
  "Impersonate another player until someone guesses who it is.",
  "Narrate everyone's movements like a nature documentary for the next two rounds.",
  "Sing everything you say for the next two rounds.",
  "Do your best catwalk across the room and back. Commit to it."
 ],
 "odds": [
  "Speak in a whisper until your next turn.",
  "Do your best impression of someone in this room until we guess who it is.",
  "Eat a teaspoon of the weirdest thing in the fridge door.",
  "Let the group choose your ringtone and keep it, loud, for a week.",
  "Show everyone the last photo in your camera roll, no context allowed.",
  "Show the group your screen time report, worst app first.",
  "Sing everything you say for the next ten minutes.",
  "Talk in an accent until someone breaks and mentions it.",
  "Do ten press-ups right now while the group provides commentary.",
  "Answer to a new name for the rest of the night, chosen by the group.",
  "Keep a straight face for one minute while everyone tries to break you.",
  "Let the person opposite restyle your hair, no mirror until it's done.",
  "Give a wedding-speech-style toast about the person on your left.",
  "Swap one item of clothing with the person opposite.",
  "Text your mum \"I've got news\" and leave it there for an hour.",
  "Let the group send one text from your phone, no edits, no deleting.",
  "Call the third contact in your phone, say \"you know what you did\", and hang up.",
  "Let the person on your right scroll your camera roll for 30 seconds.",
  "Reply \"ok x\" to the last person who messaged you, then put the phone face down.",
  "Wear your clothes backwards until the game ends.",
  "Let the group set your phone wallpaper and keep it for a week.",
  "Eat whatever sandwich the group builds from what's in the kitchen.",
  "Voice-note the group chat singing happy birthday to nobody in particular.",
  "Ask your family group chat what time your curfew is tonight.",
  "Speak only in questions until your next turn.",
  "Hold an ice cube in your fist until it has fully melted.",
  "Let the group dress you from the host's wardrobe for the next hour.",
  "Call a mate who isn't here and explain the plot of Shrek with total sincerity.",
  "Do your most committed catwalk to the kitchen and back, twice.",
  "Let the group rewrite your dating app bio, no veto.",
  "Name your actual celebrity crush, top three, ranked, with reasons.",
  "Re-enact the last thing that made you cry, interpretive dance only.",
  "Send your sibling \"don't tell mum\" and nothing else.",
  "Tell your worst hangover story in 30 seconds flat.",
  "Let the group choose your entire order at the next takeaway, no substitutions.",
  "Read out your last text thread, both sides, with feeling.",
  "Let the group read your Notes app for one full minute.",
  "Text your most recent ex \"you up?\" and show the room.",
  "Show the room your search history, ten seconds, no scrolling past anything.",
  "Take one bite of a raw onion like it's an apple.",
  "Swap phones, unlocked, with the person opposite for ten minutes.",
  "Attempt the splits, right now, no warm-up.",
  "Tell the story of your worst ever date, names redacted, nothing else redacted.",
  "Call whoever the group picks from your contacts and sing to them until they hang up.",
  "Let the group order one thing to your house on your account, under a tenner.",
  "Give a dramatic reading of your last five sent messages, out of context.",
  "Tell us the last lie you told and who you told it to.",
  "Hand your phone over, open on your DMs, for 20 seconds.",
  "Admit who in this room you'd call first for bail money, and who you'd never tell.",
  "Let the person you trust least in this room send one voice note from your phone."
 ]
};
