// Antics clean question pools for the web generators.
// Forfeit-only, alcohol-free, safe for workplaces, classrooms, weddings
// and family events. Selected with ?mode=clean or the on-page toggle.
// The app holds thousands of cards; these free pools funnel to it.
window.ANTICS_QUESTIONS_CLEAN = {
 "nhie": [
  "Pretended to know a song and mumbled my way through the whole chorus.",
  "Waved back at someone who was waving at the person behind me.",
  "Called a teacher or a boss \"mum\" or \"dad\" by accident.",
  "Said \"you too\" when a waiter told me to enjoy my meal.",
  "Pushed a door that clearly said pull, twice, in front of witnesses.",
  "Laughed at a joke I did not understand even slightly.",
  "Reheated the same cup of tea three times and drunk none of it.",
  "Forgotten someone's name halfway through introducing them.",
  "Hit reply all on an email that was meant for one person.",
  "Talked for a full minute on a call before realising I was on mute.",
  "Turned my camera off in a meeting purely so I could eat.",
  "Quietly googled something mid-conversation to pretend I already knew it.",
  "Written something on a to-do list that I had already done.",
  "Set eight alarms and comprehensively ignored every one.",
  "Photographed a whiteboard and never looked at the photo again.",
  "Said \"I'll be five minutes\" while still in the shower.",
  "Sung in the car and stopped dead at a red light.",
  "Hidden from someone I knew in a supermarket aisle.",
  "Pretended my phone was ringing to escape a conversation.",
  "Decided the last biscuit did not count because it was already broken.",
  "Bought something I did not want purely because it was on offer.",
  "Kept a houseplant alive for less than a fortnight.",
  "Assembled furniture and had parts confidently left over.",
  "Blamed a pet or a sibling for something that was entirely me.",
  "Reached the front of a queue with no idea what I wanted.",
  "Fallen asleep during a film that I chose.",
  "Told a taxi driver considerably more of my life story than necessary.",
  "Been the last person to realise a meeting had ended.",
  "Started clapping at completely the wrong moment.",
  "Rehearsed a phone call out loud before making it.",
  "Panicked and ordered exactly what the person in front of me ordered.",
  "Left a shop empty handed purely because someone offered to help.",
  "Ignored the instructions, failed, then read them in defeat.",
  "Missed my stop because I was too comfortable to move.",
  "Worn something inside out for an entire day without noticing.",
  "Screenshotted directions and then followed them completely wrong.",
  "Sent a voice note, listened back, and aged five years.",
  "Been beaten at a game by a child while genuinely trying to win.",
  "Discovered I had been saying a word wrong my entire life.",
  "Sat in the wrong seat and stayed there out of pure embarrassment.",
  "Kept a receipt for something I was never going to return.",
  "Started a series on episode two and simply carried on.",
  "Held a door open so long it became awkward for everybody.",
  "Looked extremely busy the moment someone walked past my desk.",
  "Walked off with an umbrella that was definitely not mine.",
  "Nodded along to directions I did not follow in the slightest.",
  "Been thanked for something somebody else did and said nothing.",
  "Won an argument several hours later, in the shower, alone."
 ],
 "wyr": [
  "Always be ten minutes early, or always be ten minutes late?",
  "Have unlimited free flights, or never queue for anything again?",
  "Be able to talk to animals, or speak every human language fluently?",
  "Never feel tired again, or never feel hungry again?",
  "Work four days a week for less money, or five days for more?",
  "Be brilliant at something nobody values, or average at something everybody needs?",
  "Have a rewind button for your life, or a pause button?",
  "Live somewhere it is always summer, or somewhere it is always autumn?",
  "Be the funniest person in the room, or the most interesting?",
  "Have a personal chef, or a personal driver?",
  "Only ever travel by boat, or only ever travel by train?",
  "Know every language, or understand how every machine works?",
  "Have every song you hear be one you love, or every meal be your favourite?",
  "Be able to fly slowly, or run extremely fast?",
  "Have a phone battery that never dies, or a phone that never breaks?",
  "Never lose your keys again, or never lose an argument again?",
  "Be able to breathe underwater, or survive any temperature?",
  "Get one extra hour every day, or one extra day every week?",
  "Have a photographic memory, or perfect instincts?",
  "Always say exactly what you think, or never be able to?",
  "Live in a house with no windows, or a house with no doors?",
  "Have a pause button for everyone else, or a fast forward for yourself?",
  "Only eat sweet food forever, or only savoury?",
  "Be the best player on a losing team, or the worst on a winning one?",
  "Have unlimited books, or unlimited films?",
  "Meet everyone who lived before you, or everyone who comes after?",
  "Teleport once a day, or read minds for one hour a week?",
  "Always have to tell the truth, or always be believed?",
  "Have the perfect job in a city you dislike, or an average job somewhere you love?",
  "Give up your phone for a month, or give up hot showers for a month?",
  "Be remembered for one small kindness, or one enormous achievement?",
  "Have every stranger know your name, or never be recognised again?",
  "Control the weather where you stand, or the temperature of anything you touch?",
  "Only ever whisper, or only ever shout?",
  "Have to sing everything you say, or dance everywhere you walk?",
  "Only speak in questions, or only speak in rhyme?",
  "Start every conversation with a compliment, or end every one with a joke?",
  "Wear the same outfit every day, or eat the same lunch every day?",
  "Be able to undo one thing you said, or hear one thing somebody never said?",
  "Have your work praised by strangers, or quietly by the person you admire most?"
 ],
 "mlt": [
  "Become famous for something completely accidental.",
  "Get lost with the map open in their hand.",
  "Adopt a stray animal on the way home.",
  "Start a business on a whim and make it work.",
  "Cry at an advert.",
  "Reply to an email at three in the morning.",
  "Build a spreadsheet for something that badly does not need one.",
  "Talk their way out of a parking ticket.",
  "Win a pub quiz single handed.",
  "Be recognised in a foreign country by a total stranger.",
  "Survive the longest in the wild.",
  "Panic first in an emergency, then be the most useful.",
  "Read the terms and conditions properly.",
  "Move abroad with two weeks' notice.",
  "Become extremely successful and tell nobody.",
  "Forget their own birthday.",
  "Greet a celebrity thinking they went to school together.",
  "Take a brand new hobby far too seriously within a month.",
  "Be late to their own party.",
  "Bring a guitar and refuse to be stopped.",
  "Get emotional during a wedding speech.",
  "Have a secret talent nobody here knows about.",
  "Give brilliant advice and take none of it.",
  "Be running the place in ten years.",
  "Correct somebody's pronunciation mid-sentence.",
  "Keep a receipt from years ago for no reason at all.",
  "Book a holiday they cannot afford and go anyway.",
  "Get chatting to the driver and learn their entire life story.",
  "Fall asleep first at a sleepover.",
  "Take the most photos and share none of them.",
  "Argue with a self-checkout machine and lose.",
  "Learn a whole language on an app and never speak it aloud.",
  "Turn up with the wrong sort of gift and get away with it.",
  "Be the last one dancing.",
  "Volunteer for something before hearing what it is.",
  "Bring snacks nobody asked for and save the entire day.",
  "Name a pet something ridiculous and commit to it forever.",
  "Do something kind and never mention it.",
  "Get a tattoo of an inside joke.",
  "Send a group message that was meant for one person.",
  "Have the strangest search history for entirely innocent reasons.",
  "Be the calmest person in a crisis.",
  "Reorganise somebody else's kitchen uninvited.",
  "Still be talking about this game in a year."
 ],
 "tod": [
  "What is the most useless skill you are genuinely proud of?",
  "What is something you believed for far too long?",
  "What is the worst haircut you have ever had?",
  "What is the pettiest reason you have ever fallen out with someone?",
  "What small thing annoys you far more than it reasonably should?",
  "What is the best compliment you have ever been given?",
  "What did you want to be at seven years old, and what happened?",
  "What is the most embarrassing thing your family has done in public?",
  "What do you pretend to enjoy and secretly do not?",
  "Who in this room would you want beside you in a crisis, and why?",
  "What is the worst present you have ever received?",
  "What is your most irrational fear?",
  "What rule do you break constantly and feel no guilt about?",
  "What is the longest you have gone without sleep, and why?",
  "What is a talent you completely faked your way through once?",
  "What is the nicest thing somebody in this room has done for you?",
  "What is the strangest thing in your bag or pockets right now?",
  "What was the biggest lie you told as a child?",
  "What song do you know every word to and wish you did not?",
  "What are you weirdly competitive about?",
  "Who was your first ever best friend, and where are they now?",
  "What is the worst advice you have ever actually taken?",
  "What food combination do you love that everybody else finds odd?",
  "What is the smallest thing that has ever made your whole day?",
  "Do your best impression of the player on your left until they laugh.",
  "Speak in an accent until your next turn.",
  "Give a thirty second speech praising an object in this room.",
  "Do your best catwalk across the room and back, fully committed.",
  "Invent a new dance move and teach it to the group.",
  "Narrate what everyone is doing like a wildlife documentary for two rounds.",
  "Sing everything you say for the next two rounds.",
  "Balance something on your head until your next turn.",
  "Do ten star jumps while the group provides live commentary.",
  "Make up a thirty second rap about the person on your right.",
  "Keep a completely straight face for a minute while the group tries to break you.",
  "Say the alphabet backwards as fast as you possibly can.",
  "Let the player on your left choose a new name for you until the game ends.",
  "Do an impression of somebody famous until the group guesses who.",
  "Compliment every person here, one by one, and mean it.",
  "Describe the contents of your fridge as if it were a restaurant menu.",
  "Swap one item of clothing with the player opposite. Shoes count.",
  "Talk for one minute on a subject the group picks, with no pauses.",
  "Read the last thing you wrote down on paper, out loud, with feeling.",
  "Teach the group something useful in sixty seconds."
 ],
 "odds": [
  "Speak in a whisper until your next turn.",
  "Do ten press-ups right now with the group counting.",
  "Let the group pick your lunch tomorrow, no substitutions.",
  "Sing everything you say for the next ten minutes.",
  "Answer to a new name for the rest of the day, chosen by the group.",
  "Let the person opposite restyle your hair with no mirror.",
  "Give a wedding-speech toast about the person on your left.",
  "Swap one item of clothing with the person opposite.",
  "Wear your jumper backwards until the game ends.",
  "Let the group set your phone wallpaper for a week.",
  "Hold a plank for one minute while everybody watches.",
  "Talk in an accent until somebody breaks and mentions it.",
  "Do your most committed catwalk to the door and back, twice.",
  "Keep a straight face for a minute while the group tries everything.",
  "Let the group choose your ringtone and keep it, loud, for a week.",
  "Call a friend who is not here and explain the plot of Shrek with total sincerity.",
  "Do a full lap of the building at a very serious walking pace.",
  "Speak only in questions until your next turn.",
  "Hold an ice cube in your fist until it has fully melted.",
  "Let the group pick the next three songs and dance to all of them.",
  "Tell your worst travel story in thirty seconds flat.",
  "Perform an interpretive dance of your morning routine.",
  "Let the group choose your entire takeaway order, no substitutions.",
  "Read the ingredients of something in the kitchen as though it were poetry.",
  "Attempt a cartwheel, right now, with no warm up.",
  "Balance a book on your head across the room and back.",
  "Do your best impression of the host until they notice.",
  "Sit on the floor for the rest of the round without complaint.",
  "Voice-note a friend singing happy birthday to nobody in particular.",
  "Let the group teach you a dance and perform it once, properly.",
  "Refer to yourself in the third person until your next turn.",
  "Wear a tea towel as a cape for the next twenty minutes.",
  "Give a two minute presentation on a topic the group picks, unprepared.",
  "Compliment a stranger next time you leave the house and report back.",
  "Attempt the splits, right now, with no warm up.",
  "Let the group decide what you order at the next coffee shop.",
  "Do a handstand against the wall for as long as you can manage.",
  "Recite a nursery rhyme as though it were extremely serious news.",
  "Swap seats with the person furthest from you and stay there.",
  "Let the group pick your outfit from whatever is already in the room.",
  "Give a dramatic reading of the last email you received.",
  "Whistle a song until somebody correctly guesses it.",
  "Hop everywhere you go for the next ten minutes.",
  "Deliver a serious weather forecast for this room, right now.",
  "Stand on one leg while telling us about your favourite holiday.",
  "Do your best robot walk to the kitchen and back.",
  "Let the group set an alarm on your phone for any time tomorrow.",
  "Introduce the person on your left as though they are about to win an award."
 ]
};
