// AUTO-GENERATED by ops/export-free-cards.mjs --lang es in the Antics app repo.
// Free-tier cards only (FREE_CARDS minus retired and seasonal, chosen from the
// English decks), worded from the shipped src/data/es mirror at the same
// indexes. Do not hand-edit; regenerate instead. Generated 2026-10-05T09:39:08.802Z.
window.ANTICS_FREE_ES = {
  "neverHaveIEver": [
    "Me ha gustado alguien de esta sala.",
    "He besado a alguien sin saber ni cómo se llamaba.",
    "Le he mandado un mensaje a un ex y me he arrepentido al instante.",
    "He tenido una aventura de una noche.",
    "He mandado al grupo un mensaje que era para una sola persona.",
    "He estado en un “casi algo” y me negué a llamarlo casi algo.",
    "He despertado en un lugar sin idea de cómo llegué.",
    "He ghosteado a alguien y después me lo he cruzado en persona.",
    "He mentido sobre mi body count.",
    "Me he hecho pasar por soltero/a sin serlo.",
    "He hecho la caminata de la vergüenza frente a alguien conocido.",
    "He soñado con alguien de esta sala.",
    "He vomitado en un taxi.",
    "Me he escapado antes de que la otra persona despertara.",
    "He tenido algo con alguien de este grupo de amigos.",
    "He bloqueado a alguien y luego lo desbloqueé solo para chismear.",
    "He sido infiel.",
    "He tenido amigos con derechos."
  ],
  "truths": [
    "¿A quién de esta sala besarías, si tuvieras que elegir?",
    "¿Cuál es la red flag más grande que ignoraste porque la persona estaba buenísima?",
    "¿A quién le mandaste tu último mensaje arriesgado?",
    "¿De quién fue el último perfil que miraste en redes?",
    "¿Qué es lo peor que has hecho en una salida?",
    "Si TUVIERAS que salir con alguien de esta sala, ¿con quién?",
    "¿Cuál es el peor asco repentino que te ha dado alguien?",
    "¿Cuál fue tu primera impresión honesta de tu vecino de la izquierda?",
    "¿Qué dos personas de esta sala harían la mejor pareja?",
    "¿Alguna vez has ghosteado a alguien? ¿Cuál es tu excusa?",
    "Si todos en esta sala tuvieran que besar a alguien más de la sala, ¿quién besa a quién? Tú asignas las parejas.",
    "¿Cuál es el lugar más arriesgado donde lo has hecho?",
    "¿A quién de esta sala le confiarías menos tu teléfono desbloqueado?",
    "¿Quién de esta sala sobrevive más en una película de terror, y quién muere primero?",
    "Si te cancelaran mañana, ¿por qué sería más probablemente?"
  ],
  "dares": [
    "Muéstrale al grupo tu reporte de tiempo de pantalla. Prohibido dar explicaciones.",
    "Besa a alguien de esta sala (la mejilla cuenta, cobardes).",
    "Lee en voz alta lo último que escribiste en tus notas.",
    "Haz tu mejor imitación del jugador a tu izquierda.",
    "Deja que el jugador a tu derecha mande un emoji desde tu teléfono a quien elija.",
    "Ejecuta tu paso de baile coqueto estrella a la cuenta de tres.",
    "Intercambia teléfonos con tu vecino de la izquierda hasta tu próximo turno.",
    "Demuestra tu mejor frase para ligar con tu vecino de la izquierda, con total compromiso.",
    "Gime el abecedario hasta que alguien se ría.",
    "Haz twerking por 15 segundos.",
    "Dile al grupo tu primera impresión honesta de cada uno, uno por uno.",
    "Siéntate en las piernas de tu vecino de la izquierda hasta tu próximo turno.",
    "Guíñale el ojo a cada jugador por turno. Si te devuelven el guiño, aceptas el castigo.",
    "El grupo elige una palabra que no puedes decir por el resto del juego.",
    "Ojos cerrados, describe el outfit de tu vecino de la izquierda al completo."
  ],
  "mostLikelyTo": [
    "Le escriba a un ex esta noche.",
    "Tenga algo con alguien de esta sala.",
    "Arme drama en el grupo.",
    "Ghostee a alguien de esta sala.",
    "Stalkee a su ex a las 2am.",
    "Lo echen de un antro.",
    "Tenga el “casi algo” más desastroso.",
    "Esté mintiendo en este juego ahora mismo.",
    "Termine en un reality de solteros.",
    "Tenga la galería más caótica del teléfono.",
    "Se salve de un problema a punta de coqueteo.",
    "Lea los mensajes de todos si le dieran una oportunidad gratis.",
    "Haya besado a más gente de esta sala.",
    "Se comprometa a los tres meses.",
    "Se una a una secta sin darse cuenta."
  ],
  "wouldYouRather": [
    {
      "a": "Que proyecten tu historial de búsqueda en tu próxima fiesta",
      "b": "Que impriman tus DMs y se los entreguen a tus papás"
    },
    {
      "a": "Que se filtre tu chat grupal",
      "b": "Que se filtre tu galería"
    },
    {
      "a": "Salir con tu jefe",
      "b": "Volver con tu ex"
    },
    {
      "a": "Que toda la gente que has besado entre por esa puerta ahora mismo",
      "b": "Que lean en voz alta tu último mes de DMs"
    },
    {
      "a": "Que todos sepan quién te gusta",
      "b": "Que la persona que te gusta lea todo lo que has dicho de ella"
    },
    {
      "a": "Saber exactamente cómo mueres",
      "b": "Saber exactamente cuándo mueres"
    },
    {
      "a": "Que tu body count sea de dominio público",
      "b": "Que tu saldo bancario sea de dominio público"
    },
    {
      "a": "Besar al hermano de tu mejor amigo",
      "b": "Besar al mejor amigo de tu hermano"
    },
    {
      "a": "Casarte con el mejor sexo de tu vida",
      "b": "Casarte con la mejor conversación de tu vida"
    },
    {
      "a": "Dejar el sexo por un año",
      "b": "Dejar tu teléfono por un año"
    },
    {
      "a": "Que te pillen en pleno stalkeo profundo de su perfil",
      "b": "Que te pillen ensayando una conversación con esa persona"
    },
    {
      "a": "Solo primeras citas por el resto de tu vida",
      "b": "Casado el lunes con alguien de esta sala"
    },
    {
      "a": "Hacerte un tatuaje que elija este grupo ahora mismo",
      "b": "Borrar para siempre una app que elija este grupo"
    },
    {
      "a": "Lamer el tubo del bus",
      "b": "Comerte una papa del piso del antro"
    },
    {
      "a": "Diez mil dólares ahora mismo",
      "b": "Cien a la semana de por vida"
    }
  ]
};
