// AUTO-GENERATED by ops/export-free-cards.mjs --lang pt in the Antics app repo.
// Free-tier cards only (FREE_CARDS minus retired and seasonal, chosen from the
// English decks), worded from the shipped src/data/pt mirror at the same
// indexes. Do not hand-edit; regenerate instead. Generated 2026-10-09T18:05:40.075Z.
window.ANTICS_FREE_PT = {
  "neverHaveIEver": [
    "Fiquei a fim de alguém desta sala.",
    "Beijei alguém sem nunca saber o nome.",
    "Mandei mensagem pra um ex e me arrependi na hora.",
    "Tive um caso de uma noite só.",
    "Mandei no grupo uma mensagem que era pra uma pessoa só.",
    "Vivi um “quase namoro” e me recusei a chamar de quase namoro.",
    "Acordei num lugar sem a menor ideia de como cheguei lá.",
    "Dei ghosting em alguém e depois esbarrei com a pessoa na rua.",
    "Menti sobre meu body count.",
    "Me fingi de solteiro(a) sem ser.",
    "Voltei pra casa com a roupa de ontem e dei de cara com alguém conhecido.",
    "Sonhei com alguém desta sala.",
    "Vomitei dentro de um táxi.",
    "Fugi de fininho antes de a pessoa acordar.",
    "Fiquei com alguém deste grupo de amigos.",
    "Bloqueei alguém e depois desbloqueei só pra dar uma espiada.",
    "Traí alguém.",
    "Tive uma amizade colorida."
  ],
  "truths": [
    "Quem desta sala você mais gostaria de beijar, se tivesse que escolher?",
    "Qual a maior red flag que você ignorou porque a pessoa era gata?",
    "Pra quem foi sua última mensagem ousada?",
    "Qual foi o último perfil que você olhou nas redes?",
    "Qual a pior coisa que você já fez num rolê?",
    "Se você TIVESSE que namorar alguém desta sala, quem seria?",
    "Qual o maior ranço que alguém já te deu?",
    "Qual foi sua primeira impressão honesta de seu vizinho da esquerda?",
    "Que duas pessoas desta sala dariam o melhor casal?",
    "Quem foi a última pessoa em quem você deu ghosting?",
    "Forme casais com todo mundo desta sala, pra um beijo. Quem fica com quem?",
    "Qual o lugar mais arriscado onde você já transou?",
    "Em quem desta sala você menos confiaria com seu celular desbloqueado?",
    "Quem desta sala sobrevive mais tempo num filme de terror, e quem morre primeiro?",
    "Se você fosse cancelado amanhã, qual seria o motivo mais provável?"
  ],
  "dares": [
    "Mostre pro grupo seu relatório de tempo de tela. Proibido dar explicação.",
    "Beije alguém desta sala (bochecha vale, covardes).",
    "Leia em voz alta a última coisa que você digitou no bloco de notas.",
    "Faça sua melhor imitação do jogador à sua esquerda.",
    "Deixe o jogador à sua direita mandar um emoji do seu celular pra quem ele escolher.",
    "Faça seu passinho de flerte infalível quando contarem até três.",
    "Troque de celular com seu vizinho da esquerda até a sua próxima vez.",
    "Solte sua melhor cantada pra seu vizinho da esquerda, com toda a convicção.",
    "Gema o alfabeto até alguém rir.",
    "Dance funk por 15 segundos.",
    "Diga pro grupo sua primeira impressão honesta de cada um, um por um.",
    "Sente no colo de seu vizinho da esquerda até a sua próxima vez.",
    "Pisque pra cada jogador, um por vez. Se alguém piscar de volta, você faz uma prenda.",
    "O grupo escolhe uma palavra que você não pode falar pelo resto do jogo.",
    "De olhos fechados, descreva o look de seu vizinho da esquerda dos pés à cabeça."
  ],
  "mostLikelyTo": [
    "Mande mensagem pro ex hoje à noite.",
    "Fique com alguém desta sala.",
    "Comece um barraco no grupo.",
    "Dê ghosting em alguém desta sala.",
    "Stalkeie o ex às 2 da manhã.",
    "Seja expulso(a) de uma balada.",
    "Tenha o “quase namoro” mais bagunçado.",
    "Esteja mentindo neste jogo agora mesmo.",
    "Acabe num reality de solteiros.",
    "Tenha a galeria mais caótica do celular.",
    "Escape de uma encrenca na base do flerte.",
    "Leia as mensagens de todo mundo, se tiver a chance.",
    "Tenha beijado mais gente desta sala.",
    "Fique noivo(a) com três meses de namoro.",
    "Entre numa seita sem perceber."
  ],
  "wouldYouRather": [
    {
      "a": "Ter seu histórico de busca projetado na sua próxima festa",
      "b": "Ter seus directs impressos e entregues aos seus pais"
    },
    {
      "a": "Seu grupo do zap vazar",
      "b": "Sua galeria vazar"
    },
    {
      "a": "Namorar seu chefe",
      "b": "Voltar com seu ex"
    },
    {
      "a": "Todo mundo que você já beijou entrar por essa porta agora",
      "b": "Seu último mês de directs ser lido em voz alta"
    },
    {
      "a": "Todo mundo saber de quem você tá a fim",
      "b": "A pessoa de quem você tá a fim ler tudo o que você já falou dela"
    },
    {
      "a": "Saber exatamente como você morre",
      "b": "Saber exatamente quando você morre"
    },
    {
      "a": "Seu body count virar conhecimento público",
      "b": "Seu saldo bancário virar conhecimento público"
    },
    {
      "a": "Beijar o irmão do seu melhor amigo",
      "b": "Beijar o melhor amigo do seu irmão"
    },
    {
      "a": "Casar com o melhor sexo da sua vida",
      "b": "Casar com o melhor papo da sua vida"
    },
    {
      "a": "Ficar sem sexo por um ano",
      "b": "Ficar sem celular por um ano"
    },
    {
      "a": "Ser pego(a) stalkeando a fundo o perfil do seu crush",
      "b": "Ser pego(a) ensaiando uma conversa com o seu crush"
    },
    {
      "a": "Só primeiros encontros pro resto da vida",
      "b": "Casado(a) até segunda com alguém desta sala"
    },
    {
      "a": "Fazer uma tatuagem escolhida por este grupo agora",
      "b": "Apagar pra sempre um app escolhido por este grupo"
    },
    {
      "a": "Lamber a barra do ônibus",
      "b": "Comer uma batata do chão da balada"
    },
    {
      "a": "Dez mil agora",
      "b": "Cem por semana pra vida toda"
    }
  ]
};
